[package]
name = "ergani-rust-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
ergani = { path = "ergani" }
anyhow = "1.0"
tokio = { version = "1.37.0", features = ["full"] }
chrono = "0.4"
comfy-table = "7.1.1"

[workspace]
members = ["ergani"]
