[package]
name = "ergani-rust-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ergani = { path = "ergani" }
anyhow = "1.0"
tokio = { version = "1.36.0", features = ["full"] }
chrono = "0.4"
comfy-table = "7.1.0"

[workspace]
members = ["ergani"]
