[package]
name = "ergani"
version = "0.1.7"
edition = "2021"
license = "MIT"
description = "Rust SDK for the Greek government Ergani API for employee workflows"
readme = "../README.md"
homepage = "https://github.com/pavlospt/ergani-rust-sdk"
repository = "https://github.com/pavlospt/ergani-rust-sdk"
keywords = ["ergani", "api", "sdk", "rust"]
documentation = "https://docs.rs/ergani"

[dependencies]
thiserror = "1.0.57"
anyhow = "1.0.80"
tokio = "1.36.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.114"
chrono = "0.4.34"
regex = "1.10.3"
reqwest = { version = "0.12", features = ["json"] }
async-trait = "0.1.77"
